wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.0
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.43.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720177420
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 7
      - 13
      - 23
      - 66
      4: 3.12.0
      5: 0.17.4
      6: 4.43.0.dev0
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
